// Generates docs/content-graph.md from the game's own data tables: what unlocks each place, and what each quest asks for.
//   npm run graph
import { writeFileSync, mkdirSync } from 'node:fs';
import { WEBRING, ZONES } from '../src/data/zones';
import { QUESTS } from '../src/data/quests';
import type { Cond } from '../src/core/types';

function describe(c: Cond | undefined): string {
  if (!c) return 'always';
  if ('flag' in c) return c.flag;
  if ('notFlag' in c) return `not ${c.notFlag}`;
  if ('has' in c) return `has ${c.has}`;
  if ('know' in c) return `knows ${c.know}`;
  if ('visitors' in c) return `${c.visitors}+ visitors`;
  if ('stat' in c) return `${c.stat} >= ${c.gte}`;
  if ('all' in c) return c.all.map(describe).join(' AND ');
  if ('any' in c) return c.any.map(describe).join(' OR ');
  if ('not' in c) return `not (${describe(c.not)})`;
  return JSON.stringify(c);
}
const id = (s: string) => s.replace(/[^A-Za-z0-9]/g, '_');

const lines: string[] = [];
lines.push('# Content graph', '', '_Generated by `npm run graph` from the data tables. Do not edit by hand._', '');
lines.push('## The web ring: what opens each place', '', '```mermaid', 'flowchart LR', '  home((homepage))');
for (const t of WEBRING) {
  const title = ZONES[t.zone as keyof typeof ZONES]?.title ?? t.label;
  lines.push(`  ${id(t.zone)}["${title.replace(/"/g, "'")}"]`);
  lines.push(`  home -->|"${(t.future ? 'coming soon' : describe(t.unlock)).replace(/"/g, "'")}"| ${id(t.zone)}`);
}
lines.push('```', '');
lines.push('## Quests', '', '| Quest | Starts when | Steps | Reward |', '| --- | --- | --- | --- |');
for (const q of QUESTS) {
  const steps = q.steps.map((s, i) => `${i + 1}. ${s.text} _(${describe(s.done)})_`).join('<br>');
  const reward = (q.reward ?? []).map((r) => ('id' in r ? `${r.t} ${r.id}` : 'by' in r ? `${r.t} +${r.by}` : r.t)).join(', ');
  lines.push(`| **${q.title}** | ${describe(q.start)} | ${steps} | ${reward} |`);
}
lines.push('', `${WEBRING.length} places on the ring, ${QUESTS.length} quests, ${Object.keys(ZONES).length} pages in all.`, '');
mkdirSync('docs', { recursive: true });
writeFileSync('docs/content-graph.md', lines.join('\n'));
console.log(`wrote docs/content-graph.md (${WEBRING.length} ring places, ${QUESTS.length} quests)`);
